### ISSUE TITLE
Change the position of the overlay text for OSD

### ISSUE THREAD

**Issue by novoid** [familyfriendlymikey/mpv-cut#15]
Hi,

I'd like to change the placement of the text, e.g., that gets printed via `local function text_overlay_on()` and similar.

Reason: in my setup (I don't know if this is specific to me or default behavior), when pressing `o` in mpv, I get something like "00:09:00 / 01:29:28 (7%)" at the top of the on-screen display of mpv, indicating the current playback position.

mpv-cut is also using the very same display position to write its OSD text. Therefore, I can't read both, the current playback position as well as mpv-cut information because of this issue.

I tried to find out how to change the position in lua via Internet search but failed so far. Maybe you can add an option to the source code that users might place mpv-cut information to a different position like "bottom" in my case, which separates my usual OSD information from the OSD information of mpv-cut.

Thank you!

**Comment by familyfriendlymikey** [comment]
I have this line in my `~/.config/mpv/input.conf` which might suit your use case:

```
BS script-binding osc/visibility
```

It sets backspace to turn on a progress bar at the bottom.

If not, I think prefixing the string in `text_overlay_on` would position the OSD to the bottom left:

```
text_overlay.data = string.format("{\\an1}%s in %s from %s", ACTION, channel, START_TIME)
```

But I don't know for sure. I don't have so much time to test/code it since I don't have this use case, but I'm happy to discuss/point you in the right direction and accept PRs.

Btw, thanks for your PR on the readme, will check it out when I have time.

**Comment by novoid** [comment]
I can confirm that `text_overlay.data = string.format("{\\an1}%s in %s from %s", ACTION, channel, START_TIME)` solved my issue: the OSD messages are on the bottom left above the progress bar when scrolling through the video.

My usual time indicators from above stay at the top left.

Thank you for your knowledge!
