### ISSUE TITLE
Can't cut video from EDL file

### ISSUE THREAD

**Issue by Estebiu** [familyfriendlymikey/mpv-cut#31]
When using your script on a EDL file streaming from jellyfin (using jftui), mpv_cut is unable to make cuts, be they re-encodes or lossless.

[mpv_cut] [in#0 @ 0x5d5219815900] Error opening input: Protocol not found
[mpv_cut] [in#0 @ 0x5d5219815900] Did you mean file:edl://%134%https://jellyfin.xxxxxxx.com/videos/5e6e45d5b1938b94eac2927c/stream?static=true&mediasourceid=5efa6e45d5b19385c904db94eac2927c;?
[mpv_cut] Error opening input file edl://%134%https://jellyfin.xxxxxxx.com/videos/5e6e45d5b1938b94eac2927c/stream?static=true&mediasourceid=5efa6e45d5b19385c904db94eac2927c;.
[mpv_cut] Error opening input files: Protocol not found

Would this be possible to implement or it's too much of a headache?

**Comment by familyfriendlymikey** [comment]
That might not be so straightforward since you'd probably have to read the contents of the remote edl file and then calculate where to make the cuts. Maybe it makes more sense to concat the files into one on your server instead of using an edl file, and then if need be write a custom action that takes into account the remote url as opposed to local file paths.

Unfortunately I don't have time to do this myself, sorry :/

**Comment by Estebiu** [comment]
I see.. no problem then! Feel free to close this issue.
