### ISSUE TITLE
is there anyway we can pick the Audio we want to keep?

### ISSUE THREAD

**Issue by loser1994** [familyfriendlymikey/mpv-cut#7]
I have videos with multiple audios (with my voice, chat party etc.)

Unfortunately, it always keeps the 1st audio by default. I personally don't want to keep all of them but if we could choose which audio we want to keep, this script would be perfect!

**Comment by familyfriendlymikey** [comment]
If you're doing `copy` cuts then all the audio channels will be copied as well.

If you're doing `encode` cuts, you can configure your recording software to record the content you actually want to audio channel 1.

I'm happy to continue discussing the use case with you, but I'm closing because this likely won't be added to the mpv script. Users can modify the make_cuts script to support custom use cases.
